# Generated by Django 4.0.4 on 2022-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=10, verbose_name='Цена')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цена в карточке',
                'verbose_name_plural': 'Цены в карточках',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=100, verbose_name='Услуга')),
                ('pt_old_price', models.CharField(max_length=10, verbose_name='Старая цена')),
                ('pt_new_price', models.CharField(max_length=10, verbose_name='Новая цена')),
            ],
            options={
                'verbose_name': 'Цена в таблице',
                'verbose_name_plural': 'Цены в таблице',
            },
        ),
    ]
